### ISSUE TITLE
EclipseHelper annotation indexing "inconsistency"

### ISSUE THREAD

**Issue by jaywarrick** [scijava/scijava-common#119]
I have found that depending on what what order I use classes in my program (i.e., what order I click on things in my ui) I get a different class loader provided to the EclipseHelper. This messes up annotation indexing and I get incorrect/partially duplicated class prefixes in the annotation index (to be explained). This stems from the ((URLClassLoader) loader).getURLs() call on line 140. In one case I get the sun.misc.Launcher$AppClassLoader@5cfab5b1 which returns the appropriate base/root directory of all the classes being used while running from eclipse in a maven project (i.e. the .../target/classes directory of the project(s)). In a different case (when I access functionality of ImageJ legacy prior to ImageJ2) I get java.net.URLClassLoader@5e7b876a when EclipseHelper is called which returns all the "leaves" of the directory structure (i.e., all directories that stem from the .../target/classes directory) as well as all intermediate directories and root directory. What this results in is the production of json directories plugin annotations at every directory level in of the directory structure instead of just the root .../target/classes directory. Further, due to the way that the class prefix is assembled during the directory search for indexable classes, the annotation indices at each intermediate directory and leaf directory contain incorrect class prefixes. When all is said and done, when you ask the plugin service for all plugins of type <whatever> you get multiple PluginInfo objects with incorrect class prefixes representing each directory level leading up to the class file (i.e. package1.package2.MyClass, package2.MyClass, and MyClass). Therefore, if you try to instantiate a class based on the wrong PluginInfo, you get a java.lang.NoClassDefFoundError. 

Not sure what would be the best way to handle this situation or how to influence it. Right now I just catch the NoClassDefFoundError at this specific location in my program and try the next PluginInfo to see if that will work instead while trying to instantiate my plugins - not ideal. Obviously this is a non issue if you compile your program via maven into a jar and run it but limits debugging abilities and can produce inconsistent behavior during development when running from Eclipse. I don't know enough about class loaders to know how the class loader switches when running a program and I'm not 100% positive that using legacy imagej classes prior to imagej2 classes was the issue but it is the only way I could repeat it but I don't have much debugging experience with class loaders to tell for sure. Sorry. I also apologize that I'm not savvy enought to devise an MWE project for this condition. Is there a way to find all root directories in a list of directories first then index from there or to prune away partially duplicated prefixes afterward? Would that be a bad strategy? I can help if you can think of a strategy that you would prefer to take.

Thanks!!!

**Comment by ctrueden** [comment]
Closing in favor of #370. It might not be exactly the same issue(s), but addressing #370 will demand a more thorough inspection of the `EclipseHelper` anyway.
