### ISSUE TITLE
Cache discoverable items that do not change

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#141]
During context injection, there are method and field annotation lookups, plus event handler registration, that is repeated when the results should be consistent for a given set of input parameters.

The repetition of these queries leads to significant overhead during high loads of context injection.

Thus we should be caching these results.

**Comment by hinerm** [comment]
@dietzc @ctrueden @dscho I have a partial solution on https://github.com/scijava/scijava-common/tree/cache-annotations

Aside from cleanup and documentation, do you think it's worth waiting to merge until we have a cache service that can manage these cached objects? Otherwise I'm worried about their endless proliferation. 

(also, the current caches are slightly wrong at the moment because of the recursion of the annotation scraping)

**Comment by dscho** [comment]
Hmm... I would have to spend time to wrap my head around those methods to understand the commits. Do you have any numbers about performance improvements? (If it improves how fast SCIFIO opens files, I will set aside time to review the commits, but if there are lower hanging fruits, I'd prefer to go for them first.)

**Comment by hinerm** [comment]
@dscho yes I do. Pretty graph is coming soon.

**Comment by hinerm** [comment]
Hey look, a chart
---------------------

![speedup](https://cloud.githubusercontent.com/assets/1123809/5900093/42e70f66-a52a-11e4-9b4c-8f9b8ec205ef.png)


Results from running a 7KB .tif

**Comment by hinerm** [comment]
Force pushed my latest changes, which I believe are now correct, and improve the Cache-Fixes times slightly.

**Comment by hinerm** [comment]
OK I'm happy with this now that I have semi-consolidated the `getAnnotatedMethods` and `getAnnotatedFields` logic in a way that allows for arbitrary annotation:object scrapings in a single recursion operation.

@ctrueden if you get a chance can you sign off on this? Since it's a low-level change I want another pair of eyes on it.

**Comment by ctrueden** [comment]
Wrote a bunch of comments! (They would be visible here had you filed a PR like normal people do. :stuck_out_tongue:)

**Comment by hinerm** [comment]
Continuing my trend of not acting like a normal person, I did not make a merge commit that closed this issue!

So instead, see [these commits](https://github.com/scijava/scijava-common/compare/7ae4103ac2d4503a6291c73dd3cd90f16656e821%5E...240512492ea754576819e681d1d79ce1db5270c3) which resolved this issue.
