### ISSUE TITLE
EclipseHelper: Allow to specify path to META-INF/json

### ISSUE THREAD

**Issue by dietzc** [scijava/scijava-common#149]
ClassLoaders in Eclipse-Plugins can only discover ressources inside the `src` folder of eclipse. Therefore, it would be nice, if we could specify the location where the plugin index is created (e.g. by passing a parameter `src` to the `EclipseHelper`). This shouldn't change any other code, as you try to find the ressource `META-INF/json` and you would still find it.

**Comment by ctrueden** [comment]
I think you'll have to try doing a PR for this one, and once it's working for your use case, we can merge it...

**Comment by dietzc** [comment]
Sure. I will do that!
