### ISSUE TITLE
Race condition in ConsoleServiceTest

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#159]
[This test](https://github.com/scijava/scijava-common/blob/scijava-common-2.40.0/src/test/java/org/scijava/console/ConsoleServiceTest.java#L175) is sometimes 4 instead of 6. Maybe something doesn't flush in time after disposal..?

**Comment by hinerm** [comment]
@ctrueden also got this exception:
```
3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.075 sec <<< FAILURE! - in org.scijava.console.ConsoleServiceTest
testMultipleContextOutput(org.scijava.console.ConsoleServiceTest)  Time elapsed: 0.039 sec  <<< FAILURE!
java.lang.AssertionError: expected:<6> but was:<8>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.scijava.console.ConsoleServiceTest.testMultipleContextOutput(ConsoleServiceTest.java:175)
```

in [Jenkins](http://jenkins.imagej.net/view/SciJava/job/SciJava-common/886/console)

**Comment by hinerm** [comment]
Closed by https://github.com/scijava/scijava-common/commit/d5a16e3aef41e896fa390fc25e298ddaf7c43795

**Comment by hinerm** [comment]
@ctrueden Aforementioned commit stopped this test failure.. but wasn't the intent to have the output appear synchronized so that it comes out in the correct order?

That is, with or without d5a16e3, I see output like:
```
hocus-pocus-abra-cadabra-cadavers-and-zombies-sha-clatrzameopa
```
which is clearly reordered. Or was the synchronization requirement dropped? (or made up in my brain)

**Comment by ctrueden** [comment]
The order was never deterministic, unfortunately. For now it is enough that the test always passes.
