### ISSUE TITLE
Let's make an Octave bridge!

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#187]
[Octave](https://www.gnu.org/software/octave/) is like matlab but open source.. now that we have our matlab bridge it shouldn't be that much work to do something for Octave using [javaoctave](https://kenai.com/projects/javaoctave/pages/Home)

**Comment by ctrueden** [comment]
@carandraug would be so thrilled!

**Comment by ctrueden** [comment]
No bandwidth. And it would be a separate project, not part of scijava-common.
