### ISSUE TITLE
NullPointerException in AbstractWrapperService.findWrapper(D data)

### ISSUE THREAD

**Issue by Squareys** [scijava/scijava-common#195]
Hi everybody,

I just found a `NullPointerException` being thrown in `AbstractWrapperService.findWrapper(final D data)` when plugin instantiation fails. I would instead expect it to behave like the `AbstractSingletonService`, which skips plugins for which instatiation failed. Is this correct?

Thank you in advance!
Jonathan

**Comment by ctrueden** [comment]
Good call!
