### ISSUE TITLE
Make `visibility` parameter usable from scripts

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-common#199]
It would be useful to be able to define parameter visibility in scripts, e.g. in Python:

    # @String(label="Label", visibility="message", value="My message") text

In a Java command, this can currently be done using the enum `org.scijava.ItemVisibility`:

    @Parameter(persist = false,
               visibility = org.scijava.ItemVisibility.MESSAGE,
               required = false)
    private String message= null;

The `enum` doesn't seem to be accessible during parameter harvesting in scripts, so this might require a fall-back to `String`s, similar to the [`style` parameter](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/plugin/Parameter.java#L132-L141).

**Comment by ctrueden** [comment]
Hmm. In theory, the visibility parameter is supposed to work. There is [code for it in `ScriptInfo`](https://github.com/scijava/scijava-common/blob/scijava-common-2.48.0/src/main/java/org/scijava/script/ScriptInfo.java#L481-L483). Something is broken under the hood.

**Comment by imagejan** [comment]
Oh yes, thanks, indeed it works like that:

```
# @String(label="Label", visibility="MESSAGE", value="My message", persist=false) text
```

I was trying:

```
# @String(label="Label", visibility="message", value="My message") text
```

or:

```
# @String(label="Label", visibility=org.scijava.ItemVisibility.MESSAGE, value="My message") text
```

 ... which didn't work.
In addition, I needed to add `persist=false`, otherwise it could've happened that I see some text entered into a 'text' parameter in a different script (see also https://github.com/scijava/scijava-common/issues/193).

So I'll close this issue.

**Comment by ctrueden** [comment]
I believe it also works to leave off the quotes, so you should be able to write `visibility=MESSAGE` if that appeals to you more.

**Comment by imagejan** [comment]
> I believe it also works to leave off the quotes, so you should be able to write visibility=MESSAGE if that appeals to you more.

Oh yes, true, I should have tried that! :-) Thanks a lot @ctrueden !

**Comment by ctrueden** [comment]
Note that addressing #156 might affect how enums are handled. I think we will definitely want to keep supporting `visibility=MESSAGE` (without quotes) though, since that is most similar to the Java syntax.

**Comment by ctrueden** [comment]
Addressing #156 _did_ break `visibility=MESSAGE` without the quotes. But as of 28479f33e8bb6409cb74623debf3470b3c5c6078, this should work again.
