### ISSUE TITLE
Make sure that script commands are in the correct menu

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-common#201]
The menu commands for scripts can end up in the wrong place when their subdirectory names are equal, e.g. Fiji's `plugins/Scripts/Registration/Correct_3D_drift.py` and any other script in a folder named `Registration`, e.g. `plugins/Scripts/foo/Registration/my_bar.py` (see [this forum thread](http://forum.imagej.net/t/menu-entry-for-script-provided-via-update-site/292/4)).

The cause is presumably in [`ScriptFinder`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/script/ScriptFinder.java#L79-L98) or in [`DefaultScriptService`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/script/DefaultScriptService.java), and [`ScriptFinderTest`](https://github.com/scijava/scijava-common/blob/master/src/test/java/org/scijava/script/ScriptFinderTest.java) should include a test for this situation.

**Comment by ctrueden** [comment]
Initial investigation shows that the bug is related to the ImageJ Legacy UI. The problem does not occur in the ImageJ Swing UI, nor in the underlying data structures.

**Comment by ctrueden** [comment]
Commit 8703451480fccd7d0603639836d1cc36e8a837bf introduces a unit test which I expected would exhibit this bug, but actually works fine. The issue is something to do with how SciJava modules get added to the legacy ImageJ UI's menu structure.

**Comment by imagejan** [comment]
@ctrueden Thanks for investigating! So then it's more likely somewhere in [these lines of `IJ1Helper.java`](https://github.com/imagej/imagej-legacy/blob/master/src/main/java/net/imagej/legacy/IJ1Helper.java#L654-L783). I'm getting confused in the IJ1/IJ2 legacy jungle...
Should we move the issue?

**Comment by ctrueden** [comment]
@imagejan Would you please test whether imagej/imagej-legacy#129 fixes the issue for you?

**Comment by imagejan** [comment]
@ctrueden Amazing! Tested it, works like a charm. :+1:
