### ISSUE TITLE
UIService.show(Object o) shows legacy dialog when the current UI is in modern mode

### ISSUE THREAD

**Issue by LeonYang5114** [scijava/scijava-common#204]
Code to reproduce the problem:
```
ImageJ ij = new ImageJ();
ij.ui().showUI("swing");
Dataset blobs = ij.scifio().datasetIO().open("http://imagej.net/images/blobs.gif");
ij.ui().show(blobs);
```
The code above shows two dialogs of the same image, but one of legacy UI and the other of modern UI. Closing the dialog of legacy UI closes both dialogs, but not vise versa.

A workaround for now is replacing the last line to:
`ij.ui().getUI("swing").show(blobs);`

This might due to the fact that the [AbstractUserInterface#show(name, o)](https://github.com/scijava/scijava-common/blob/35163f8e93e526ab75f710f014f4600ded4398b4/src/main/java/org/scijava/ui/AbstractUserInterface.java#L115) tries to create a display, which also creates two dialogs (one in legacy and one in modern mode). 

I think the expected behavior should be only showing the current UI, which is the modern UI in this case. Any idea?

**Comment by LeonYang5114** [comment]
Just recognize that the correct way to use the swing UI programmatically is to set it as the default UI. The code above thus becomes:
```
ImageJ ij = new ImageJ();
ij.ui().setDefaultUI(ij.ui().getUI("swing"));
ij.ui().showUI();
Dataset blobs = ij.scifio().datasetIO().open("http://imagej.net/images/blobs.gif");
ij.ui().show(blobs);
```
Then the legacy dialog will not pop up.

**Comment by ctrueden** [comment]
Another way that should work:
```java
ImageJ ij = new ImageJ();
ij.ui().showUI("swing");
uis = ij.ui().getVisibleUIs();
Dataset blobs = ij.scifio().datasetIO().open("http://imagej.net/images/blobs.gif");
uis.get(0).show(blobs);
```
