### ISSUE TITLE
Consider making OptionsPlugin abstract

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#208]
It's confusing that `OptionsPlugin` is a concrete class as this implies there may be a reason to construct an instance of `OptionsPlugin`... I see no reason this would ever be done.

My preference would be for an `OptionsPlugin` interface and converting the existing `OptionsPlugin` to an abstract class.

**Comment by hinerm** [comment]
@ctrueden I think we talked about this before when I was implementing an `OptionsPlugin`... I vaguely recall there may be a reason for `OptionsPlugin` to be non-abstract. Do you remember?

**Comment by ctrueden** [comment]
I do not remember. IMO, it should have been abstract all along.
