### ISSUE TITLE
String default values are not used to to populate dialog input fields

### ISSUE THREAD

**Issue by axtimwalde** [scijava/scijava-common#223]
I am using script parameters1 in Beanshell and woiuld like to populate dialog fields with default values. Yet, the input fields are empty.

    // @String(label="Server base URL",value="http://forum.imagej.net") server
    import ij.IJ;
    IJ.log(server);

**Comment by ctrueden** [comment]
See also [this forum thread](http://forum.imagej.net/t/script-parameters-default-values-to-populate-dialog-input-fields/792/).

**Comment by ctrueden** [comment]
So, after some digging: it seems the Swing widgets respect the default value only for numeric types. I don't know WTF I was thinking when I did this: https://github.com/scijava/scijava-ui-swing/commit/7dc0af5e65ee3238f0d5116bba25dd7f35c438e8. It is horribly un-general.

**Comment by ctrueden** [comment]
Fixed in 4679622b50e31cbc8c2920490dae983ab00aeea8.
