### ISSUE TITLE
Only add return value if no declared outputs

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#225]
Right now a return value is added if there isn't a parameter [with the name "return"](https://github.com/scijava/scijava-common/blob/40c2f7863e5f974539aa13c7822dabb65d2ed8a4/src/main/java/org/scijava/script/ScriptInfo.java#L349-L371). I suggest that we instead only add the default return value if no OUTPUT or BOTH parameters are declared.

I think this would also involve changing the logic of [getReturnValue](https://github.com/scijava/scijava-common/blob/40c2f7863e5f974539aa13c7822dabb65d2ed8a4/src/main/java/org/scijava/script/ScriptModule.java#L133).. either to the first/last OUTPUT parameter, or a list of all OUTPUT parameters..

**Comment by hinerm** [comment]
any thoughts @ctrueden ?

**Comment by ctrueden** [comment]
I agree with the first paragraph 100%. The second part—changing the logic of `getReturnValue`, I think we shouldn't do. That method gets the actual return value of the script, and I think it's fine to leave it as is. Unless I am missing something...?

**Comment by ctrueden** [comment]
Fixed with the merge of #242.
