### ISSUE TITLE
Migrate JavaRunner logic to SJC

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#226]
The JavaRunner plugins(https://github.com/scijava/scripting-java/blob/scripting-java-0.3.5/src/main/java/org/scijava/plugins/scripting/java/JavaRunner.java) are not scripting-specific. They should be migrated to SJC and the RunArgument ConsoleArgument plugin should be refactored to simply use the JavaRunner framework.

**Comment by ctrueden** [comment]
Started work on the `run-classes` branch. Not complete yet.
