### ISSUE TITLE
Create ProcessorService

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#232]
Pre and Postprocessor plugins [seem like a good candidate](https://github.com/scijava/scijava-common/tree/25ede181f744ae50f90576487197f7f7a2789791/src/main/java/org/scijava/module/DefaultModuleService.java#L352-L362) to be singleton plugins, managed by a `ProcessorService`.

**Comment by ctrueden** [comment]
Yeah, good idea. I'm not sure why I didn't make the singletons before. I cannot think of a reason this wouldn't work.

However, note that the typical `SingletonService` pattern manages a single type of `SingletonPlugin`. The fact that we have two here (`PreprocessorPlugin` and `PostprocessorPlugin`) might complicate matters.

**Comment by hinerm** [comment]
As it turns out, these plugins are stateful (cancelable) and thus should not be singletons. See #239
