### ISSUE TITLE
Canceling status applies to all subsequent commands

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#239]
Steps:

1. Open script editor
1. Run `# @String(label = "Monty Hall", choices = { "Door A", "Door B", "Door C" }) montyHall` as jython script (or any input that will pop a cancelable dialog)
1. Cancel the input dialog
1. All other commands will now be immediately canceled when run (e.g. run `Help > Update...`)

**Comment by hinerm** [comment]
see https://github.com/scijava/scijava-common/tree/fix-cancelation

**Comment by hinerm** [comment]
problem is that if a preprocessor is canceled, it retains that state. preprocessors are singletons so all subsequent modules are auto-canceled.

**Comment by ctrueden** [comment]
Best bug ever. Thanks for fixing it quickly, @hinerm!
