### ISSUE TITLE
Single file parameter  in script opens file dialog that ignores default value

### ISSUE THREAD

**Issue by axtimwalde** [scijava/scijava-common#248]
A @File parameter with a specified value opens a file dialog at an arbitrary directory without the default value being considered.  Multiple @File parameters generate a dialog with correctly defaulted file fields.

I am experiencing this on Fiji's script editor, Beanshell, Ubuntu 16.04, OpenJDK 8 in case that any of this matters.

The expected behavior would be that the file dialog opens in the parent directory specified in value with the file specified in value being selected, alternatively the dialog could be opened like with any other parameter.

**Comment by ctrueden** [comment]
@axtimwalde Thanks for the bug report.

I took a crack at fixing this. But in my quick test just now, the above commit does not seem to fix it. Feel free to test it yourself, and/or dig further, since this gives a hint where I think the problem lies. I have to run now, but will try to find time to come back to this soon.

**Comment by ctrueden** [comment]
Actually, there were two separate bugs, which both needed to be fixed to fully resolve this:

* 6d81fd7c2319d001dba3084579bc45b524ed8850
* imagej/imagej-legacy@9ac976236a61d4fdbac55d639e56b12b37dce0ed

If you like, you can test using the following artifact builds:

* [imagej-legacy-0.23.2-SNAPSHOT.jar](http://maven.imagej.net/service/local/artifact/maven/redirect?r=snapshots&g=net.imagej&a=imagej-legacy&v=0.23.2-SNAPSHOT&e=jar)
* [scijava-common-2.60.2-SNAPSHOT.jar](http://maven.imagej.net/service/local/artifact/maven/redirect?r=sonatype-snapshots&g=org.scijava&a=scijava-common&v=2.60.2-SNAPSHOT&e=jar)

They will be released within a few days.
