### ISSUE TITLE
inconsistent ClassUtils.getAnnotatedFields() implementation?

### ISSUE THREAD

**Issue by tpietzsch** [scijava/scijava-common#252]
The javadoc of [`ClassUtils.getAnnotatedFields(...)`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/util/ClassUtils.java#L410-L433) says it returns *A new list containing all fields with the requested annotation*. However, it sometimes returns a new list, and sometimes the cached list.
```
	public static <A extends Annotation> List<Field> getAnnotatedFields(
		final Class<?> c, final Class<A> annotationClass)
	{
		List<Field> fields = fieldCache.getList(c, annotationClass);

		if (fields == null) {
			fields = new ArrayList<>();
			getAnnotatedFields(c, annotationClass, fields);
		}

		return fields;
	}
```

Is this an oversight or intended behaviour?

(same for `getAnnotatedMethods(...)`)

**Comment by ctrueden** [comment]
Thanks @tpietzsch. I updated the javadoc to reflect the current reality. See the commit for further details.
