### ISSUE TITLE
NullPointerException when running ScriptModule

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-common#269]
Consider the following:

```groovy
#!groovy

#@ScriptService scripts
#@ModuleService modules

scriptFile = new File("C:\\scripts\\Process_Single_File_with_String.groovy")
scriptInfo = scripts.getScript(scriptFile)

module = scriptInfo.createModule()
instance = modules.run(module, true)

println(instance.get())
```

with the script file `Process_Single_File_with_String.groovy` containing:

```groovy
#!groovy

#@File input
#@String name
#@LogService log

log.info("Hello $name, now processing $input")
```

Running the first script will output:

```text
[INFO] Hello Jan, now processing C:\temp
[ERROR] Module threw exception
java.lang.NullPointerException
	at org.scijava.script.ScriptModule.run(ScriptModule.java:180)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:237)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Am I missing something here?

The [line](https://github.com/scijava/scijava-common/blob/cc99b9ba3f2e8bb556055ac808b8f4a7500d5132/src/main/java/org/scijava/script/ScriptModule.java#L180) in question is during the processing of outputs:
```java
final Object typed = conversionService.convert(decoded, item.getType());
```

See the related [forum post](http://forum.imagej.net/t/scijava-batch-processor/5548/5?u=imagejan).

**Comment by imagejan** [comment]
It seems like I have to inject the context before using the `ModuleService` to run a `ScriptModule`.

Add these two lines solves the issue:

```groovy
#@ImageJ ij
module.setContext(ij.getContext())
```

**Comment by ctrueden** [comment]
Instead of using:
```groovy
module = scriptInfo.createModule()
```
Try:
```groovy
module = modules.createModule(scriptInfo)
```
As you discovered, the former does not inject the context, while the former does. This is because the `ScriptInfo` instance is not contextual, but the `ModuleService` is. We should probably change this in the future, since the lack of context in some areas of the module framework creates tricky pitfalls like this.
