### ISSUE TITLE
addAll is not null safe in getAnnotatedFields method in ClassUtils class

### ISSUE THREAD

**Issue by NicoKiaru** [scijava/scijava-common#325]
https://github.com/scijava/scijava-common/blob/5641c206c127d2d153cd1a511aafba1892877772/src/main/java/org/scijava/util/ClassUtils.java#L196

Could be solved by a simple test. A warning message displaying which annotatedFields are null could be useful for debugging purpose.

**Comment by ctrueden** [comment]
This is in response to the exception you posted, right? The reason I was reluctant to add a null test here is: _why_ is this method being called with a null list, rather than an empty list? Isn't that a bug somewhere in the calling code? I was nervous about "papering over" such a bug at this low level, without first investigating more thoroughly.

**Comment by NicoKiaru** [comment]
Perfectly agree. I tried to debug the exception I got - but this method was called too many times correctly before the exception shows up... At some point I gave up. I believe a test followed by a meaningful error message (displaying all relevant information - at least all the parameters called) when a null cachedFields shows up could be useful. Whether this is useful for debugging purpose only, or in the deployed code, I don't know.

**Comment by ctrueden** [comment]
> this method was called too many times correctly before the exception shows up...

You could try using an "exception breakpoint." ([IntelliJ](https://www.jetbrains.com/help/idea/creating-exception-breakpoints.html), [Eclipse](https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-catching_exceptions.htm)) Then you can inspect the state of the VM at the time the exception is thrown.

This null cachedFields thing should never happen in production... I would rather that field caching logic not be present at all, actually—it was a deep change for pure performance reasons that should probably have been solved in a different way.

I will try to return to investigating this later. In the meantime, if you could please post an MCVE illustrating the issue, that would make my life a lot easier.

**Comment by NicoKiaru** [comment]
This never happened again. It was related  to a jar file not being detected as far as I remember. I don t remeber exactly and I have no mcve.

**Comment by ctrueden** [comment]
Thanks for following up, @NicoKiaru!
