### ISSUE TITLE
Improve ObjectService with names for objects

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-common#371]
The `ObjectService` can be used quite flexibly to keep track of registered objects of any kind. To improve user experience, it would be useful to be able to specify names/identifiers for registered objects, though.

For example, the `DefaultWidgetModel` currently displays choice labels that are generated from each object's `toString` method:

https://github.com/scijava/scijava-common/blob/06aa06d7d5e7f6eec8f2f23a27cba7e686a5b8c6/src/main/java/org/scijava/widget/DefaultWidgetModel.java#L225-L233

We could improve this by checking for the object's name via `getName` if the object implements `org.scijava.Named`. However, many objects we might want to register in practice don't implement this interface, e.g. `RealTransform` (from `imglib2`) or `BdvHandle` (from `bigdataviewer`) (@NicoKiaru, @tischi), `Node` (from `sciview`) (@kephale), or `SpotCollection` (from `TrackMate`).

To allow for more flexibility here, I'd like to suggest adding new API to `ObjectService`:

* `void addObject(Object object, String name)` allowing to add an object with a specified name, and
* `Map<String, Object> getObjectMap()` retrieving a map of names and objects.

In addition, we could change `addObject(Object object)` to automatically try `getName` and fall back to `toString` if no name is provided explicitly.

I vaguely remember that naming objects was mentioned in some discussion somewhere (maybe @ctrueden can recall better).

If that's a feasible change, we would most likely also need to change/improve the underlying [`ObjectIndex`](https://github.com/scijava/scijava-common/blob/06aa06d7d5e7f6eec8f2f23a27cba7e686a5b8c6/src/main/java/org/scijava/object/ObjectIndex.java) implementation.

**Comment by NicoKiaru** [comment]
Thanks for starting this discussion @imagejan !

I can recall a discussion on gitter here:
https://gitter.im/scijava/scijava-common?at=5d9c6278940b4c2fc096b63e

If you want to allow to access `Object`s with a `Map<String, Object>`, how would you ensure the unicity of names ? Would you allow for non-unique names if the `Objet` class is different ?

**Comment by imagejan** [comment]
Thanks for linking to the discussion, @NicoKiaru!

Ah yes, `Map<String,Object>` probably wouldn't work without a *lot* of effort, and seeing how `ObjectIndex` is currently used (in `PluginService`, `ModuleService` etc.), I'd rather not mess with it ;-)

And I don't think we should disallow duplicate names, but rather leave it to the caller if they want to enforce uniqueness when adding objects.

We could maybe extend `ObjectIndex` by a new `NamedObjectIndex` (similar to [`SortedObjectIndex`](https://github.com/scijava/scijava-common/blob/06aa06d7d5e7f6eec8f2f23a27cba7e686a5b8c6/src/main/java/org/scijava/object/SortedObjectIndex.java)) and then just keep track of a `Map<Object,String>` for the names.

(The same object can be in the `ObjectIndex` multiple times, but that wouldn't matter for the map, as we'd have a single name per object.)

**Comment by ctrueden** [comment]
Thanks @imagejan for all your work on this.
