### ISSUE TITLE
Parameter autoFill attribute not respected in scripts

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-common#376]
Consider the following script:

```groovy
#@ Dataset (autoFill=false) img
println img
```

While I would expect a dialog with a dropdown choice to appear here, the parameter is always auto-filled (by `ActiveDatasetPreprocessor` from `imagej-common`, but it contains logic similar to `org.scijava.module.process.AbstractSingleInputPreprocessor`, so I'm filing it here).

The same issue with parameters types `Img`, `ImagePlus` etc., and tested also with `persist=false` and `required=false`.

We need to check if `item.isAutoFill()` really returns `false` in these cases. I don't think there's a test for this specific attribute yet, is there?

**Comment by imagejan** [comment]
The problem seems to be `DefaultMutableModuleItem` which lacks and override for `isAutoFill()` and therefore will always return `true` (inherited from `AbstractModuleItem`):

https://github.com/scijava/scijava-common/blob/560ad964a7a1e859edd4dbe4fc48d7d9e09523f2/src/main/java/org/scijava/module/DefaultMutableModuleItem.java#L43-L74

This script:

```groovy
#@ ModuleService ms
#@ ScriptService ss

import net.imagej.Dataset

script = """
\n#@ Dataset (autofill=false) img
println img
"""

module = ss.run(".groovy", script, true).get()
imgInput = module.getInfo().getInput("img")

println imgInput.class
println imgInput.isAutoFill()
```

outputs:

```
class org.scijava.module.DefaultMutableModuleItem
true
```

**Comment by ctrueden** [comment]
Thanks so much for the report and fix!
